apiVersion: v1
kind: Service
metadata:
  name: slee-svc
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    web: webexpre
  ports:
    - name: http
      port: 80
      # protocol: TCP
      targetPort: 80


